# Generated by Django 4.2.7 on 2024-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ключ верификации'),
        ),
    ]
