# Generated by Django 4.2.7 on 2024-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailDeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название рассылки')),
                ('time_start', models.DateTimeField(verbose_name='Начало рассылки')),
                ('time_stop', models.DateTimeField(verbose_name='Окончание рассылки')),
                ('periodicity', models.CharField(choices=[('Раз в час', 'Раз в час'), ('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю')], max_length=70, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=70, verbose_name='Статус')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
